llms:
  llm_type: "huggingface" # openai, huggingface, chatopenai
  temperature: 0.5
  model_name: "facebook/bart-large-cnn"
  task: "summarization"
#  api_key: "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"
  api_key: "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"

vector_store:
  vector_type: "faiss"  # Options: "chroma", "faiss"
  data_path: "./db"
  resource_path: "./resource"

embeddings:
  embedding_type: "huggingface" # huggingface=HuggingFaceEmbeddings, openai=OpenAIEmbeddings, etc
  embedding_model: "sentence-transformers/all-mpnet-base-v2" #"sentence-transformers/all-MiniLM-L6-v2"
#  index_size: 768


